---
title: "Prob. classifiers"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Prob. classifiers}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
rm(list=ls())
```

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(learningmachine)
library(caret)
library(palmerpenguins)
library(mlbench)
library(skimr)
library(reshape2)
library(pROC)
library(reticulate)
```

# 1 - Using `Classifier` object

```{r}
set.seed(43)
X <- as.matrix(iris[, 1:4])
# y <- factor(as.numeric(iris$Species))
y <- iris$Species

index_train <- base::sample.int(n = nrow(X),
                                 size = floor(0.8*nrow(X)),
                                 replace = FALSE)
X_train <- X[index_train, ]
y_train <- y[index_train]
X_test <- X[-index_train, ]
y_test <- y[-index_train]
dim(X_train)
dim(X_test)

obj <- learningmachine::Classifier$new(method = "ranger")
obj$get_type()
obj$get_name()
obj$set_B(10)
obj$set_level(95)

t0 <- proc.time()[3]
obj$fit(X_train, y_train, pi_method="kdesplitconformal")
cat("Elapsed: ", proc.time()[3] - t0, "s \n")

probs <- obj$predict_proba(X_test)
```

```{r fig.width=8, fig.height=4, eval=TRUE}
df <- reshape2::melt(probs$sims$setosa[1:3, ])
df$Var2 <- NULL 
colnames(df) <- c("individual", "prob_setosa")
df$individual <- as.factor(df$individual)
ggplot2::ggplot(df, aes(x=individual, y=prob_setosa)) + geom_boxplot() + coord_flip()
```

```{r fig.width=8, fig.height=4, eval=TRUE}
ggplot2::ggplot(df, aes(x=prob_setosa, fill=individual)) + geom_density(alpha=.3)
```

```{r}
obj$summary(X_test, y=y_test, 
            class_name = "setosa",
            show_progress=FALSE)
```

# 2 - `ranger` classification

```{r}
obj <- learningmachine::Classifier$new(method = "ranger")
obj$set_level(95)
obj$set_pi_method("bootsplitconformal")
t0 <- proc.time()[3]
obj$fit(X_train, y_train)
cat("Elapsed: ", proc.time()[3] - t0, "s \n")

probs <- obj$predict_proba(X_test)
```

```{r fig.width=8, fig.height=4, eval=TRUE}
df <- reshape2::melt(probs$sims$setosa[1:3, ])
df$Var2 <- NULL 
colnames(df) <- c("individual", "prob_setosa")
df$individual <- as.factor(df$individual)
ggplot2::ggplot(df, aes(x=individual, y=prob_setosa)) + geom_boxplot() + coord_flip()
```

```{r fig.width=8, fig.height=4, eval=TRUE}
ggplot2::ggplot(df, aes(x=prob_setosa, fill=individual)) + geom_density(alpha=.3)
```

```{r}
obj$summary(X_test, y=y_test, 
            class_name = "setosa",
            show_progress=FALSE)
```

# 3 - `extratrees` classification

```{r}
obj <- learningmachine::Classifier$new(method = "extratrees")
obj$set_level(95)
t0 <- proc.time()[3]
obj$fit(X_train, y_train, 
        pi_method = "bootsplitconformal")
cat("Elapsed: ", proc.time()[3] - t0, "s \n")
```

```{r}
probs <- obj$predict_proba(X_test)
```

```{r fig.width=8, fig.height=4, eval=TRUE}
df <- reshape2::melt(probs$sims$virginica[1:3, ])
df$Var2 <- NULL 
colnames(df) <- c("individual", "prob_virginica")
df$individual <- as.factor(df$individual)
ggplot2::ggplot(df, aes(x=individual, y=prob_virginica)) + geom_boxplot() + coord_flip()
```

```{r fig.width=8, fig.height=4, eval=TRUE}
ggplot2::ggplot(df, aes(x=prob_virginica, fill=individual)) + geom_density(alpha=.3)
```

```{r}
obj$summary(X_test, y=y_test, 
            class_name = "virginica",
            show_progress=FALSE)
```

# 4 - Penguins dataset

```{r}
library(palmerpenguins)
data(penguins)
```

```{r}
penguins_ <- as.data.frame(palmerpenguins::penguins)

replacement <- median(penguins$bill_length_mm, na.rm = TRUE)
penguins_$bill_length_mm[is.na(penguins$bill_length_mm)] <- replacement

replacement <- median(penguins$bill_depth_mm, na.rm = TRUE)
penguins_$bill_depth_mm[is.na(penguins$bill_depth_mm)] <- replacement

replacement <- median(penguins$flipper_length_mm, na.rm = TRUE)
penguins_$flipper_length_mm[is.na(penguins$flipper_length_mm)] <- replacement

replacement <- median(penguins$body_mass_g, na.rm = TRUE)
penguins_$body_mass_g[is.na(penguins$body_mass_g)] <- replacement

# replacing NA's by the most frequent occurence
penguins_$sex[is.na(penguins$sex)] <- "male" # most frequent

# one-hot encoding for covariates
penguins_mat <- model.matrix(species ~., data=penguins_)[,-1]
penguins_mat <- cbind.data.frame(penguins_$species, penguins_mat)
penguins_mat <- as.data.frame(penguins_mat)
colnames(penguins_mat)[1] <- "species"

y <- penguins_mat$species
X <- as.matrix(penguins_mat[,2:ncol(penguins_mat)])

n <- nrow(X)
p <- ncol(X)

set.seed(1234)
index_train <- sample(1:n, size=floor(0.8*n))
X_train <- X[index_train, ]
y_train <- factor(y[index_train])
X_test <- X[-index_train, ][1:5, ]
y_test <- factor(y[-index_train][1:5])
```

```{r}
obj <- learningmachine::Classifier$new(method = "extratrees")
obj$set_pi_method("bootsplitconformal")
obj$set_level(95)
obj$set_B(10L)
t0 <- proc.time()[3]
obj$fit(X_train, y_train)
cat("Elapsed: ", proc.time()[3] - t0, "s \n")
```

```{r eval=TRUE}
probs <- obj$predict_proba(X_test)
```

```{r fig.width=8, fig.height=4, eval=TRUE}
df <- reshape2::melt(probs$sims[[1]][1:3, ])
df$Var2 <- NULL 
colnames(df) <- c("individual", "prob_Adelie")
df$individual <- as.factor(df$individual)
ggplot2::ggplot(df, aes(x=individual, y=prob_Adelie)) + geom_boxplot() + coord_flip()
```

```{r fig.width=8, fig.height=4, eval=TRUE}
ggplot2::ggplot(df, aes(x=prob_Adelie, fill=individual)) + geom_density(alpha=.3)
```

```{r}
obj$summary(X_test, y=y_test, 
            class_name = "Adelie",
            show_progress=FALSE)
```

<!-- # 4 - `mlbench` `BreastCancer` dataset -->

<!-- ```{r} -->
<!-- library(mlbench) -->
<!-- data(BreastCancer) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- breast_cancer <- BreastCancer -->
<!-- breast_cancer$Id <- NULL -->
<!-- ``` -->

<!-- ```{r} -->
<!-- replacement <- 10L -->
<!-- breast_cancer$Bare.nuclei[is.na(breast_cancer$Bare.nuclei)] <- replacement -->
<!-- breast_cancer$Bare.nuclei <- as.factor(as.integer(breast_cancer$Bare.nuclei)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- y <- breast_cancer$Class -->
<!-- X <- as.matrix(model.matrix(Class ~.,  -->
<!--                             data=breast_cancer)[,-1]) -->
<!-- rownames(X) <- NULL -->
<!-- colnames(X) <- base::gsub(pattern = "\\.|\\^", replacement = "_", colnames(X)) -->

<!-- n <- nrow(X) -->
<!-- p <- ncol(X) -->

<!-- set.seed(1234) -->
<!-- index_train <- sample(1:n, size=floor(0.8*n)) -->
<!-- X_train <- X[index_train, ] -->
<!-- y_train <- y[index_train] -->
<!-- X_test <- X[-index_train, ][1:5,] -->
<!-- y_test <- y[-index_train][1:5] -->
<!-- ``` -->

<!-- ```{r} -->
<!-- obj <- learningmachine::Classifier$new(method = "extratrees") -->
<!-- obj$set_level(95) -->
<!-- obj$set_B(10L) -->
<!-- obj$set_pi_method("kdesplitconformal") -->
<!-- t0 <- proc.time()[3] -->
<!-- obj$fit(X_train, y_train) -->
<!-- cat("Elapsed: ", proc.time()[3] - t0, "s \n") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- probs <- obj$predict_proba(X_test) -->
<!-- preds <- obj$predict(X_test) -->
<!-- ``` -->

<!-- ```{r fig.width=8, fig.height=4, eval=TRUE} -->
<!-- df <- reshape2::melt(probs$sims$malignant[1:3, ]) -->
<!-- df$Var2 <- NULL  -->
<!-- colnames(df) <- c("individual", "prob_malignant") -->
<!-- df$individual <- as.factor(df$individual) -->
<!-- ggplot2::ggplot(df, aes(x=individual, y=prob_malignant)) + geom_boxplot() + coord_flip() -->
<!-- ``` -->

<!-- ```{r fig.width=8, fig.height=4, eval=TRUE} -->
<!-- ggplot2::ggplot(df, aes(x=prob_malignant, fill=individual)) + geom_density(alpha=.3) -->
<!-- ``` -->

<!-- ```{r eval=FALSE} -->
<!-- obj$summary(X_test, y=y_test,  -->
<!--             class_name = "malignant", -->
<!--             show_progress=FALSE) -->
<!-- ``` -->

<!-- **KDE** -->

<!-- ```{r} -->
<!-- probs <- obj$predict_proba(X_test) -->
<!-- preds <- obj$predict(X_test) -->
<!-- ``` -->

<!-- ```{r fig.width=8, fig.height=4, eval=TRUE} -->
<!-- df <- reshape2::melt(probs$sims$malignant[1:3, ]) -->
<!-- df$Var2 <- NULL  -->
<!-- colnames(df) <- c("individual", "prob_malignant") -->
<!-- df$individual <- as.factor(df$individual) -->
<!-- ggplot2::ggplot(df, aes(x=individual, y=prob_malignant)) + geom_boxplot() + coord_flip() -->
<!-- ``` -->

<!-- **Bootstrap** -->

<!-- ```{r eval=TRUE} -->
<!-- obj <- learningmachine::Classifier$new(method = "ridge") -->
<!-- obj$set_pi_method("bootsplitconformal") -->
<!-- obj$set_level(95) -->
<!-- obj$set_B(10L) -->
<!-- obj$fit(X_train, y_train) -->
<!-- probs <- obj$predict_proba(X_test) -->
<!-- preds <- obj$predict(X_test) -->
<!-- ``` -->

<!-- ```{r fig.width=8, fig.height=4, eval=TRUE} -->
<!-- df2 <- reshape2::melt(probs$sims$malignant[1:3,]) -->
<!-- df2$Var2 <- NULL  -->
<!-- colnames(df2) <- c("individual", "prob_malignant") -->
<!-- df2$individual <- as.factor(df$individual) -->
<!-- ggplot2::ggplot(df2, aes(x=individual, y=prob_malignant)) + geom_boxplot() + coord_flip() -->
<!-- ``` -->

<!-- ```{r fig.width=8, fig.height=4, eval=TRUE} -->
<!-- ggplot2::ggplot(df2, aes(x=prob_malignant, fill=individual)) + geom_density(alpha=.3) -->
<!-- ``` -->

<!-- ```{r eval=FALSE} -->
<!-- obj$summary(X_test, y=y_test,  -->
<!--             class_name = "malignant", -->
<!--             show_progress=FALSE) -->
<!-- ``` -->
