# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_cpp <- function(x, y) {
    .Call(`_learningmachine_crossprod_cpp`, x, y)
}

l2_norm <- function(x) {
    .Call(`_learningmachine_l2_norm`, x)
}

na_matrix <- function(n, p) {
    .Call(`_learningmachine_na_matrix`, n, p)
}

weighted_l2_norm <- function(x, l) {
    .Call(`_learningmachine_weighted_l2_norm`, x, l)
}

matern32_kxx_cpp <- function(x, l) {
    .Call(`_learningmachine_matern32_kxx_cpp`, x, l)
}

matern32_kxstar_cpp <- function(newx, x, l) {
    .Call(`_learningmachine_matern32_kxstar_cpp`, newx, x, l)
}

derivs <- function(x, c, l) {
    .Call(`_learningmachine_derivs`, x, c, l)
}

inters <- function(x, j1, j2, c, l) {
    .Call(`_learningmachine_inters`, x, j1, j2, c, l)
}

inters2 <- function(x, j1, j2, c, l) {
    .Call(`_learningmachine_inters2`, x, j1, j2, c, l)
}

solve_eigen <- function(Eigenvectors, Eigenvalues, y, lambda) {
    .Call(`_learningmachine_solve_eigen`, Eigenvectors, Eigenvalues, y, lambda)
}

find_lam_eigen <- function(Eigenvectors, Eigenvalues, y, lambda_vector) {
    .Call(`_learningmachine_find_lam_eigen`, Eigenvectors, Eigenvalues, y, lambda_vector)
}

rcpp_hello_world <- function() {
    .Call(`_learningmachine_rcpp_hello_world`)
}

