# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

crossprod_cpp <- function(x, y) {
    .Call(`_learningmachine_crossprod_cpp`, x, y)
}

l2_norm <- function(x) {
    .Call(`_learningmachine_l2_norm`, x)
}

na_matrix <- function(n, p) {
    .Call(`_learningmachine_na_matrix`, n, p)
}

weighted_l2_norm <- function(x, l) {
    .Call(`_learningmachine_weighted_l2_norm`, x, l)
}

matern32_kxx_cpp <- function(x, l) {
    .Call(`_learningmachine_matern32_kxx_cpp`, x, l)
}

matern32_kxstar_cpp <- function(newx, x, l) {
    .Call(`_learningmachine_matern32_kxstar_cpp`, newx, x, l)
}

derivs <- function(x, c, l) {
    .Call(`_learningmachine_derivs`, x, c, l)
}

inters <- function(x, j1, j2, c, l) {
    .Call(`_learningmachine_inters`, x, j1, j2, c, l)
}

inters2 <- function(x, j1, j2, c, l) {
    .Call(`_learningmachine_inters2`, x, j1, j2, c, l)
}

solve_eigen <- function(Eigenvectors, Eigenvalues, y, reg_lambda) {
    .Call(`_learningmachine_solve_eigen`, Eigenvectors, Eigenvalues, y, reg_lambda)
}

find_lam_eigen <- function(Eigenvectors, Eigenvalues, y, reg_lambda_vector) {
    .Call(`_learningmachine_find_lam_eigen`, Eigenvectors, Eigenvalues, y, reg_lambda_vector)
}

fastSampleCpp <- function(resids, n) {
    .Call(`_learningmachine_fastSampleCpp`, resids, n)
}

empirical_quantile_cpp <- function(x, q) {
    .Call(`_learningmachine_empirical_quantile_cpp`, x, q)
}

row_quantiles_cpp <- function(mat, q) {
    .Call(`_learningmachine_row_quantiles_cpp`, mat, q)
}

calculate_quantiles_cpp <- function(sims, level, n_classes) {
    .Call(`_learningmachine_calculate_quantiles_cpp`, sims, level, n_classes)
}

simulate_gaussian_mixture_cpp <- function(x, n, p, width) {
    .Call(`_learningmachine_simulate_gaussian_mixture_cpp`, x, n, p, width)
}

